### ISSUE TITLE
Pre-trained weights only for English text?

### ISSUE THREAD

**Issue by abghaky** [YuzheZhang-1999/DiffTSR#17]
Thank you for the great work.

I want to use your code for text super-resolution of some very noisy/blurry text images. However, 
I noticed that since the pre-trained weights are generated based on Chinese and English text, I get incorrect results for some characters due to high distortions. By any chance, do you have any pre-trained weights using only English text? If not, how can I retrain the model for English only, and should I retrain from scratch, or only fine-tune? 

Here is a sample result for your reference.

Input:
![c4_input](https://github.com/user-attachments/assets/8f8f7b6b-6eea-4f63-9b1b-9c4f38c7abee)

Output:
![c4](https://github.com/user-attachments/assets/e96d2a8f-1778-4416-9589-8acc285580be)

**Comment by YuzheZhang-1999** [comment]
Thank you for your interest in our work.

While the IDM model was not pretrained solely on English datasets, it was trained on a mixed dataset with Chinese, English, and numbers, allowing it to generalize to English text images in most cases.  However, if you want IDM to perform optimally on text images in specific scenarios, such as document or web text, fine-tuning on these particular datasets would be beneficial.

Additionally, I noticed that the images you provided may suffer from quality issues due to potential bias in the TDM model's distribution.  To address this, you may consider fine-tuning TDM or replacing it with a text recognition model better suited to your requirements.

**Comment by abghaky** [comment]
Thank you for your reply.
