### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by 8600862** [YuzheZhang-1999/DiffTSR#9]
just run python inference_DiffTSR.py
RuntimeError: Error(s) in loading state_dict for Transformer:
        size mismatch for embedding_word.lut.weight: copying a param with shape torch.Size([7937, 512]) from checkpoint, the shape in current model is torch.Size([23558, 512]).
        size mismatch for generator_word.proj.weight: copying a param with shape torch.Size([7937, 1024]) from checkpoint, the shape in current model is torch.Size([23558, 1024]).
        size mismatch for generator_word.proj.bias: copying a param with shape torch.Size([7937]) from checkpoint, the shape in current model is torch.Size([23558]).

**Comment by YuzheZhang-1999** [comment]
Thank you for your attention and interest.
This error is quite unusual because, as long as the model configuration file hasn't been modified, a loading error shouldn't occur. Could you have made changes to some parts of the code? If you could provide more information, it would help me assess the situation.
